version: '3.9'
services:
  database:
    image: mysql:latest
    container_name: database
    restart: always
    command: --character-set-server=utf8mb4 --sql-mode="TRADITIONAL"
    working_dir: /home
    volumes:
      - ./scripts:/home - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: very_secret
volumes:
  mysql_data:
